Q1

In [1]:
import numpy as np

In [2]:
np.__version__

'1.19.2'

Q2

In [3]:
import pandas

In [4]:
pandas.__version__

'1.1.3'

In [5]:
import urllib.request
url = 'https://raw.githubusercontent.com/alexeygrigorev/mlbookcamp-code/master/chapter-02-car-price/data.csv'
filename = 'data.csv'
urllib.request.urlretrieve(url, filename)

('data.csv', <http.client.HTTPMessage at 0x1c70cc12400>)

In [6]:
import pandas as pd
df = pd.read_csv('data.csv')

In [7]:
df.head()

Make       Model  Year             Engine Fuel Type  Engine HP  \
0  BMW  1 Series M  2011  premium unleaded (required)      335.0   
1  BMW    1 Series  2011  premium unleaded (required)      300.0   
2  BMW    1 Series  2011  premium unleaded (required)      300.0   
3  BMW    1 Series  2011  premium unleaded (required)      230.0   
4  BMW    1 Series  2011  premium unleaded (required)      230.0   

   Engine Cylinders Transmission Type     Driven_Wheels  Number of Doors  \
0               6.0            MANUAL  rear wheel drive              2.0   
1               6.0            MANUAL  rear wheel drive              2.0   
2               6.0            MANUAL  rear wheel drive              2.0   
3               6.0            MANUAL  rear wheel drive              2.0   
4               6.0            MANUAL  rear wheel drive              2.0   

                         Market Category Vehicle Size Vehicle Style  \
0  Factory Tuner,Luxury,High-Performance      Compact         Coupe   
1                     Luxury,Performance      Compact   Convertible   
2                Luxury,High-Performance      Compact         Coupe   
3                     Luxury,Performance      Compact         Coupe   
4                                 Luxury      Compact   Convertible   

   highway MPG  city mpg  Popularity   MSRP  
0           26        19        3916  46135  
1           28        19        3916  40650  
2           28        20        3916  36350  
3           28        18        3916  29450  
4           28        18        3916  34500

In [8]:
 print(df["Make"])

0            BMW
1            BMW
2            BMW
3            BMW
4            BMW
          ...   
11909      Acura
11910      Acura
11911      Acura
11912      Acura
11913    Lincoln
Name: Make, Length: 11914, dtype: object


In [9]:
dfnew = df[df['Make'] == 'BMW']  
print(dfnew)

      Make       Model  Year             Engine Fuel Type  Engine HP  \
0      BMW  1 Series M  2011  premium unleaded (required)      335.0   
1      BMW    1 Series  2011  premium unleaded (required)      300.0   
2      BMW    1 Series  2011  premium unleaded (required)      300.0   
3      BMW    1 Series  2011  premium unleaded (required)      230.0   
4      BMW    1 Series  2011  premium unleaded (required)      230.0   
...    ...         ...   ...                          ...        ...   
11901  BMW          Z4  2016  premium unleaded (required)      240.0   
11902  BMW          Z4  2016  premium unleaded (required)      335.0   
11903  BMW          Z8  2001  premium unleaded (required)      394.0   
11904  BMW          Z8  2002  premium unleaded (required)      394.0   
11905  BMW          Z8  2003  premium unleaded (required)      394.0   

       Engine Cylinders Transmission Type     Driven_Wheels  Number of Doors  \
0                   6.0            MANUAL  rear wheel d

In [10]:
dfnew.describe()

Year   Engine HP  Engine Cylinders  Number of Doors  \
count   334.000000  334.000000        334.000000       334.000000   
mean   2014.347305  326.907186          5.958084         3.161677   
std       4.387983  105.681659          1.728939         0.988324   
min    1995.000000  170.000000          0.000000         2.000000   
25%    2015.000000  240.000000          4.000000         2.000000   
50%    2016.000000  300.000000          6.000000         4.000000   
75%    2016.000000  394.000000          7.500000         4.000000   
max    2017.000000  600.000000         12.000000         4.000000   

       highway MPG    city mpg  Popularity           MSRP  
count   334.000000  334.000000       334.0     334.000000  
mean     29.245509   20.739521      3916.0   61546.763473  
std      10.257037   13.136879         0.0   27982.682153  
min      18.000000   10.000000      3916.0    4697.000000  
25%      25.000000   17.000000      3916.0   42300.000000  
50%      28.000000   20.000000      3916.0   51850.000000  
75%      33.000000   22.000000      3916.0   79725.000000  
max     111.000000  137.000000      3916.0  141200.000000

Q4

In [11]:
df_new2 = df[df['Year'] >= 2015]  
df_new2['Engine HP'].isnull().sum()

51

Question 5

Calculate the average "Engine HP" in the dataset.
Use the fillna method and to fill the missing values in "Engine HP" with the mean value from the previous step.
Now, calcualte the average of "Engine HP" again.

Has it changed?

Round both means before answering this questions. You can use the round function for that:

In [12]:
df[['Engine HP']] = df[['Engine HP']].fillna(value = 326.907186)

In [13]:
df.describe()

Year     Engine HP  Engine Cylinders  Number of Doors  \
count  11914.000000  11914.000000      11884.000000     11908.000000   
mean    2010.384338    249.835034          5.628829         3.436093   
std        7.579740    109.033999          1.780559         0.881315   
min     1990.000000     55.000000          0.000000         2.000000   
25%     2007.000000    170.000000          4.000000         2.000000   
50%     2015.000000    227.000000          6.000000         4.000000   
75%     2016.000000    302.000000          6.000000         4.000000   
max     2017.000000   1001.000000         16.000000         4.000000   

        highway MPG      city mpg    Popularity          MSRP  
count  11914.000000  11914.000000  11914.000000  1.191400e+04  
mean      26.637485     19.733255   1554.911197  4.059474e+04  
std        8.863001      8.987798   1441.855347  6.010910e+04  
min       12.000000      7.000000      2.000000  2.000000e+03  
25%       22.000000     16.000000    549.000000  2.100000e+04  
50%       26.000000     18.000000   1385.000000  2.999500e+04  
75%       30.000000     22.000000   2009.000000  4.223125e+04  
max      354.000000    137.000000   5657.000000  2.065902e+06

In [14]:
mean_hp_before = 326.907186
mean_hp_after = 249.835034
print(round(mean_hp_before))
print(round(mean_hp_after))

327
250


Question 6

Select all the "Rolls-Royce" cars from the dataset.
Select only columns "Engine HP", "Engine Cylinders", "highway MPG".
Now drop all duplicated rows using drop_duplicates method (you should get a dataframe with 7 rows).
Get the underlying NumPy array. Let's call it X.
Compute matrix-matrix multiplication between the transpose of X and X. To get the transpose, use X.T. Let's call the result XTX.
Invert XTX.
What's the sum of all the elements of the result?
Hint: if the result is negative, re-read the task one more time

In [15]:
df_Rolls = df[df['Make'] == 'Rolls-Royce']  
print(df_Rolls)

              Make                   Model  Year             Engine Fuel Type  \
2921   Rolls-Royce                Corniche  2001  premium unleaded (required)   
3505   Rolls-Royce                    Dawn  2016  premium unleaded (required)   
5275   Rolls-Royce         Ghost Series II  2015  premium unleaded (required)   
5276   Rolls-Royce         Ghost Series II  2015  premium unleaded (required)   
5277   Rolls-Royce         Ghost Series II  2016  premium unleaded (required)   
5278   Rolls-Royce         Ghost Series II  2016  premium unleaded (required)   
5279   Rolls-Royce                   Ghost  2012  premium unleaded (required)   
5280   Rolls-Royce                   Ghost  2012  premium unleaded (required)   
5281   Rolls-Royce                   Ghost  2013  premium unleaded (required)   
5282   Rolls-Royce                   Ghost  2013  premium unleaded (required)   
5283   Rolls-Royce                   Ghost  2014  premium unleaded (required)   
5284   Rolls-Royce          

In [16]:
df_arry = df_Rolls[["Engine HP", "Engine Cylinders", "highway MPG"]]
df_arry

Engine HP  Engine Cylinders  highway MPG
2921       325.0               8.0           15
3505       563.0              12.0           19
5275       563.0              12.0           21
5276       563.0              12.0           21
5277       563.0              12.0           21
5278       563.0              12.0           21
5279       563.0              12.0           20
5280       563.0              12.0           20
5281       563.0              12.0           21
5282       563.0              12.0           21
5283       563.0              12.0           21
5284       563.0              12.0           21
7443       322.0              12.0           15
7444       322.0              12.0           15
7553       453.0              12.0           19
7554       453.0              12.0           19
7555       453.0              12.0           19
7556       453.0              12.0           19
7557       453.0              12.0           19
7558       453.0              12.0           19
7559       453.0              12.0           19
7560       453.0              12.0           19
7561       453.0              12.0           19
7562       453.0              12.0           19
7563       453.0              12.0           19
7564       453.0              12.0           19
9431       322.0              12.0           15
9432       322.0              12.0           15
11448      624.0              12.0           21
11449      624.0              12.0           21
11450      624.0              12.0           21

In [17]:
df_arry.drop_duplicates()
df_arry

Engine HP  Engine Cylinders  highway MPG
2921       325.0               8.0           15
3505       563.0              12.0           19
5275       563.0              12.0           21
5276       563.0              12.0           21
5277       563.0              12.0           21
5278       563.0              12.0           21
5279       563.0              12.0           20
5280       563.0              12.0           20
5281       563.0              12.0           21
5282       563.0              12.0           21
5283       563.0              12.0           21
5284       563.0              12.0           21
7443       322.0              12.0           15
7444       322.0              12.0           15
7553       453.0              12.0           19
7554       453.0              12.0           19
7555       453.0              12.0           19
7556       453.0              12.0           19
7557       453.0              12.0           19
7558       453.0              12.0           19
7559       453.0              12.0           19
7560       453.0              12.0           19
7561       453.0              12.0           19
7562       453.0              12.0           19
7563       453.0              12.0           19
7564       453.0              12.0           19
9431       322.0              12.0           15
9432       322.0              12.0           15
11448      624.0              12.0           21
11449      624.0              12.0           21
11450      624.0              12.0           21

In [22]:
df_arry2 = df_arry.drop_duplicates(subset=['Engine HP','highway MPG'])
df_arry2

Engine HP  Engine Cylinders  highway MPG
2921       325.0               8.0           15
3505       563.0              12.0           19
5275       563.0              12.0           21
5279       563.0              12.0           20
7443       322.0              12.0           15
7553       453.0              12.0           19
11448      624.0              12.0           21

In [25]:
X = df_arry2.to_numpy()

In [26]:
X

array([[325.,   8.,  15.],
       [563.,  12.,  19.],
       [563.,  12.,  21.],
       [563.,  12.,  20.],
       [322.,  12.,  15.],
       [453.,  12.,  19.],
       [624.,  12.,  21.]])

In [27]:
XT = X.transpose()
XT

array([[325., 563., 563., 563., 322., 453., 624.],
       [  8.,  12.,  12.,  12.,  12.,  12.,  12.],
       [ 15.,  19.,  21.,  20.,  15.,  19.,  21.]])

In [35]:
XTX = np.dot(XT,X)
XTX

array([[1.754801e+06, 3.965600e+04, 6.519600e+04],
       [3.965600e+04, 9.280000e+02, 1.500000e+03],
       [6.519600e+04, 1.500000e+03, 2.454000e+03]])

Sum

In [36]:
Sum_Result = M_Results.sum()
Sum_Result

1970887.0

**Questions 7**


Create an array y with values [1000, 1100, 900, 1200, 1000, 850, 1300].

Multiply the inverse of XTX with the transpose of X, and then multiply the result by y. Call the result w.
What's the value of the first element of w?.

In [54]:
y = [1000, 1100, 900, 1200, 1000, 850, 1300]

In [55]:
y = np.array(y)
y

array([1000, 1100,  900, 1200, 1000,  850, 1300])

In [60]:
TXTX = np.linalg.inv(XTX)
TXTX

array([[ 5.17815728e-05,  9.06587044e-04, -1.92984188e-03],
       [ 9.06587044e-04,  1.05723058e-01, -8.87084092e-02],
       [-1.92984188e-03, -8.87084092e-02,  1.05900809e-01]])

In [61]:
MResults = np.dot(TXTX,XT)
MResults

array([[-0.00486592,  0.00336507, -0.00049461,  0.00143523, -0.00139492,
        -0.0023309 ,  0.00266407],
       [-0.19020088,  0.09362543, -0.08379139,  0.00491702,  0.22997159,
        -0.00609915, -0.02848958],
       [ 0.25164625, -0.13888652,  0.0729151 , -0.03298571, -0.09739786,
         0.07339609, -0.04480526]])

In [62]:
w = np.dot(MResults,y)
w

array([ 0.19989598, 31.02612262, 31.65378877])

In [63]:
w[0]

0.19989598183185642